// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherFinderAPI.Models;

namespace WeatherFinderAPI.Migrations
{
    [DbContext(typeof(LocationContext))]
    [Migration("20200609005333_LocationsDB")]
    partial class LocationsDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("WeatherFinderAPI.Models.LocationItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Lat")
                        .HasColumnType("REAL");

                    b.Property<string>("LocName")
                        .HasColumnType("TEXT");

                    b.Property<double>("Lon")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("LocationItems");
                });
#pragma warning restore 612, 618
        }
    }
}
